# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "mumd",
    "mum",
    "mumctl",
    "mumlib"
]

[profile.release]
lto = "thin"
