[package]
name = "mumctl"
version = "0.1.0"
authors = ["Gustav Sörnäs <gustav@sornas.net>",
           "Eskil Queseth <eskilq@kth.se>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mumlib = { path = "../mumlib" }

clap = { version = "2.33", features = ["yaml"] }
colored = "2.0"
log = "0.4"
ipc-channel = "0.14"

#cursive = "0.15"
