[package]
name = "mumlib"
version = "0.1.0"
authors = ["Gustav Sörnäs <gustav@sornas.net>",
           "Eskil Queseth <eskilq@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
fern = "0.5"
log = "0.4"
mumble-protocol = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
