[package]
name = "mumd"
version = "0.2.0"
authors = ["Gustav Sörnäs <gustav@sornas.net>",
           "Eskil Queseth <eskilq@kth.se>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["notifications"]

notifications = ["libnotify"]

[dependencies]
mumlib = { path = "../mumlib" }

argparse = "0.2"
bytes = "1.0"
cpal = { git = "https://github.com/RustAudio/cpal" }
dasp_interpolate = { version = "0.11", features = ["linear"] }
dasp_signal = "0.11"
futures = "0.3"
futures-util = "0.3"
hound = "3.4"
ipc-channel = "0.14"
log = "0.4"
mumble-protocol = { path="../../rust-mumble-protocol" }
native-tls = "0.2"
openssl = { version = "0.10" }
opus = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "net", "time"] }
tokio-native-tls = "0.3"
tokio-util = { version = "0.6", features = ["codec", "net"] }

libnotify = { version = "1.0", optional = true }

#compressor = "0.3"
#daemonize = "0.4"
