[package]
name = "mumd"
version = "0.2.0"
authors = ["Gustav Sörnäs <gustav@sornas.net>",
           "Eskil Queseth <eskilq@kth.se>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["notifications", "sound-effects"]

notifications = ["libnotify"]

sound-effects = ["hound", "dasp_signal", "dasp_interpolate"]

[dependencies]
mumlib = { path = "../mumlib" }

argparse = "0.2"
bytes = "0.5"
cpal = { git = "https://github.com/RustAudio/cpal" }
futures = "0.3"
futures-util = "0.3"
ipc-channel = "0.14"
log = "0.4"
mumble-protocol = "0.3"
native-tls = "0.2"
openssl = { version = "0.10" }
opus = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["blocking", "macros", "rt-core", "sync", "tcp", "time"] }
tokio-tls = "0.3"
tokio-util = { version = "0.3", features = ["codec", "udp"] }

libnotify = { version = "1.0", optional = true }

dasp_signal = { version = "0.11", optional = true }
dasp_interpolate = { version = "0.11", features = ["linear"], optional = true }
hound = { version = "3.4", optional = true }

#compressor = "0.3"
#daemonize = "0.4"
